In [2]:
import numpy as np

Crie uma matriz de 10 zeros

In [4]:
matriz_10_zeros = np.zeros(10)

In [6]:
matriz_10_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crie uma matriz de 10 zeros

In [7]:
matriz_10_ones = np.ones(10)

In [9]:
matriz_10_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
matriz_10_cincos = np.ones(10)*5

In [15]:
matriz_10_cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
array1 = np.arange(10, 51)

In [19]:
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [21]:
array_pares = np.arange(10, 51, 2)

In [23]:
array_pares

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [71]:

matriz_3x3 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [72]:
matriz_3x3 = np.array(matriz_3x3)

In [73]:
matriz_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
identidade = np.eye(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
aleatorios = np.random.rand(1)

In [75]:
aleatorios

array([0.85253527])

In [76]:
aleatorios_25_numeros = np.random.rand(25)

In [78]:
aleatorios_25_numeros

array([0.40500884, 0.14150007, 0.94624738, 0.56103971, 0.1883089 ,
       0.87970791, 0.82442839, 0.21762277, 0.77024647, 0.37905836,
       0.54401512, 0.6317328 , 0.10784161, 0.68076305, 0.41065867,
       0.25446667, 0.31520718, 0.82495203, 0.57689351, 0.50325724,
       0.8450933 , 0.79982182, 0.27711786, 0.08195558, 0.16239328])

In [85]:
matriz_cem = np.arange(1, 101)/100

In [87]:
matriz_cem

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [90]:
matriz_20_espacado = np.linspace(0, 1)

In [92]:
matriz_20_espacado

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [95]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [97]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [99]:
mat[3:4,4:]

array([[20]])

In [101]:
mat[:3,1:2 ]

array([[ 2],
       [ 7],
       [12]])

In [103]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
mat.sum()

325

In [107]:
mat.std()

7.211102550927978

In [111]:
soma_colunas = mat.sum(axis=0)

In [113]:
soma_colunas

array([55, 60, 65, 70, 75])