In [2]:
import numpy as np

In [3]:
minha_lista = [1, 2, 3]

In [5]:
minha_lista # 1 dimensão

[1, 2, 3]

In [7]:
minha_array = np.array(minha_lista)
minha_array

array([1, 2, 3])

In [9]:
duas_dimensoes = [[1, 2, 3], [4, 5, 6]] # 2 dimensões
np.array(duas_dimensoes )

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
tres_dimensoes = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # 3 dimensões
np.array(tres_dimensoes)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(1, 10, 2) 

array([1, 3, 5, 7, 9])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.linspace(1, 50, 100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [40]:
np.random.rand(5) # 5 números de 0 a 1 seguindo uma distribuição uniforme.

array([0.81284851, 0.05515924, 0.32741745, 0.60829268, 0.43502707])

In [41]:
np.random.rand(5, 4) # Uma matriz de 5 por 4 com números de 0 a 1

array([[0.48705262, 0.55981713, 0.31001452, 0.15552202],
       [0.87128326, 0.27089273, 0.19905466, 0.13915542],
       [0.40038306, 0.04559925, 0.68897724, 0.03476027],
       [0.76079732, 0.137972  , 0.78724211, 0.06659705],
       [0.99232499, 0.60187171, 0.21747604, 0.6109542 ]])

In [44]:
np.random.rand(3, 3, 3) # Largura, comprimento e profundidade

array([[[0.93040426, 0.4151964 , 0.98087329],
        [0.73101589, 0.03311549, 0.027793  ],
        [0.13842724, 0.15118189, 0.11530921]],

       [[0.9954007 , 0.50736614, 0.61841638],
        [0.47121882, 0.78331166, 0.23546958],
        [0.525298  , 0.58534291, 0.43838165]],

       [[0.14786526, 0.73670702, 0.27801039],
        [0.30931938, 0.42503554, 0.1641354 ],
        [0.47269601, 0.01634503, 0.76604546]]])

In [53]:
np.random.randn(4) # Distribuição normal, média 0 e desvio padrão 1

array([-0.47958262, -0.24691292,  1.65983447,  0.20491203])

In [64]:
np.random.randint(1, 10, 3) # Pega números aleatórios de 1 a 10

array([6, 3, 5])

In [83]:
arr = np.random.rand(8)

In [84]:
arr

array([0.71927312, 0.99377699, 0.00279471, 0.04622976, 0.40860179,
       0.51596825, 0.65392425, 0.51772385])

In [88]:
arr.reshape(4, 2)

array([[0.71927312, 0.99377699],
       [0.00279471, 0.04622976],
       [0.40860179, 0.51596825],
       [0.65392425, 0.51772385]])

In [90]:
arr.shape # Mostra quantos número existem

(8,)

In [92]:
arr.max()

0.9937769949982524

In [94]:
arr.min()

0.002794706525614754

In [96]:
arr.argmax() # Retorna o índice do maior número

1

In [99]:
arr.argmin() # Retorna o índice de menor número

2