In [2]:
import numpy as np

In [4]:
minha_lista = [1,2,3]

In [6]:
minha_lista

[1, 2, 3]

In [8]:
np.array(minha_lista) #Vai converter minha lista em um Array de Python

array([1, 2, 3])

In [41]:
minha_matriz = [[1,2,3], [4,5,6],[7,8,9]]

In [42]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [43]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0, 10, 2) #Cria uma sequência de números pulando de acordo com a constante dada

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
arr = np.zeros((5,5))

In [21]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
arr2 = np.ones((10,10))

In [26]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
np.eye(5) # Cria uma matrix identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.linspace(0,10,5) # Números igualmente espaçados

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.random.rand(5) # Números entre 0 e 1

array([0.42469892, 0.42439044, 0.63407891, 0.04026034, 0.5726336 ])

In [34]:
np.random.rand(5)*100

array([10.76874076, 73.11050237,  1.28880452, 58.2719509 , 96.47545452])

In [40]:
np.random.rand(5,5) # 5 Linhas e 5 colunas

array([[0.26683624, 0.60506285, 0.65664814, 0.07219063, 0.24575883],
       [0.98358892, 0.98916947, 0.55795573, 0.90099782, 0.5373007 ],
       [0.32354004, 0.54696975, 0.49322039, 0.03733208, 0.08137548],
       [0.58747683, 0.01834956, 0.67787268, 0.0949604 , 0.15404765],
       [0.57802386, 0.88606492, 0.07563212, 0.96866293, 0.41192734]])

In [46]:
np.random.rand(5,5,5) # Matriz de 3 dimensões

array([[[0.11226686, 0.41101553, 0.8949404 , 0.62541293, 0.80804859],
        [0.42722274, 0.36502138, 0.75773439, 0.07710651, 0.86814642],
        [0.55556212, 0.07673833, 0.97401641, 0.14669676, 0.2185736 ],
        [0.27550779, 0.81458563, 0.56706881, 0.21258889, 0.69993486],
        [0.611321  , 0.27809555, 0.59477331, 0.4147495 , 0.89528181]],

       [[0.25936819, 0.4724705 , 0.30360956, 0.1417511 , 0.81744926],
        [0.36825193, 0.54133619, 0.29698329, 0.79598761, 0.38971757],
        [0.25124129, 0.33705384, 0.66061451, 0.90384407, 0.52345509],
        [0.77077816, 0.85501357, 0.58221714, 0.79231811, 0.7466835 ],
        [0.26400925, 0.76781739, 0.61837441, 0.15355486, 0.12664941]],

       [[0.14439359, 0.74246295, 0.73230747, 0.33979383, 0.98099121],
        [0.53016459, 0.83141691, 0.04649642, 0.94120418, 0.98811825],
        [0.46927495, 0.6529577 , 0.69976601, 0.69684284, 0.6819886 ],
        [0.00754721, 0.36521082, 0.88087802, 0.81485305, 0.54768264],
        [0.04966

In [48]:
np.random.randn(4) # Distribuição Gauciana (ver em estatística)

array([ 1.21152631, -1.85754075,  1.97945738,  0.80852937])

In [50]:
np.random.randint(0,100,10) # Tirei 10 números dentro intervalo de 100 números.

array([37, 14, 64, 12, 92, 54, 18, 27, 91, 91])

In [52]:
arr3 = np.random.rand(25)

In [54]:
arr3

array([0.85330211, 0.37637641, 0.19333427, 0.03922693, 0.1665034 ,
       0.36049464, 0.75574165, 0.08455085, 0.54629931, 0.88482039,
       0.31480003, 0.96784231, 0.68795002, 0.72266137, 0.12444883,
       0.65090284, 0.06597885, 0.68661198, 0.38942139, 0.08726501,
       0.81554447, 0.19829855, 0.91548467, 0.78415996, 0.86252147])

In [69]:
arr3.reshape((5,5))

array([[0.85330211, 0.37637641, 0.19333427, 0.03922693, 0.1665034 ],
       [0.36049464, 0.75574165, 0.08455085, 0.54629931, 0.88482039],
       [0.31480003, 0.96784231, 0.68795002, 0.72266137, 0.12444883],
       [0.65090284, 0.06597885, 0.68661198, 0.38942139, 0.08726501],
       [0.81554447, 0.19829855, 0.91548467, 0.78415996, 0.86252147]])

In [70]:
arr3.shape

(25,)

In [72]:
arr.shape

(5, 5)

In [74]:
arr3.max()

0.9678423128545947

In [76]:
arr3.min()

0.039226930637082824

In [78]:
arr3.argmax() # Vai retornar o índice na qual o maior elemento se encontra.

11

In [80]:
arr3.argmin() # Vai retornar o índice na qual o menor elemento se encontra.

3